### PR TITLE
DFA-2034 - make cookie secure

### PR DESCRIPTION
**Pull request by BorisP-GDS**
## Why

Make the cookie secure on production

As we are using cross domain cookie and we are making update to our cross domain script in  Product pages , we need to make the update here as well, because this repo uses the cross domain cookie script as well.

At the moment secure cookie settings is not enabled, this PR enables it.

### CODE REVIEW

**Review by CharlesIC — APPROVED** [review]

**Comment by sabrinaharris** [comment]
@BorisP-GDS Could you add a bit more context to the PR about why this change is needed and any other relevant information please?

**Comment by BorisP-GDS** [comment]
@sabrinaharris More details added.

**Comment by BorisP-GDS** [comment]
@sabrinaharris , are you able to review this PR ? It has already been approved by DFA tech lead.

**Review by sabrinaharris — APPROVED** [review]

**Comment by sabrinaharris** [comment]
> @sabrinaharris , are you able to review this PR ? It has already been approved by DFA tech lead.

@BorisP-GDS Approved :)

**Pull request merged**
