### PR TITLE
Draft note clarifying sub-building-name field

### PR DESCRIPTION
**Pull request by galund**
This suggested documentation change is in response to some confusion that arose in a relying party team, quote

> Thanks for your email and sending the offending address in the format we can use for debugging. I confirm that this is an issue as described by the user and the "Apartment M" being dropped.
> The reason for that is, our parsing routine assumes that if "buildingName" is empty then there's no reason for a value expected in "subBuildingName". 
> I understand that this might be impossible to tell but was this a wrong assumption ? or is this an odd address occurrence ?

Opening this as a draft as I don't have a local running copy of these docs, and the strange formatting / spans etc make it a bit difficult to be sure that I'm suggesting the right thing!

### CODE REVIEW

**Comment by PippaClarkGDS** [comment]
Cheers @galund - I can take a look at this later this week with our new tech writer

**Comment by PippaClarkGDS** [comment]
hiya @galund - thanks for raising this PR. I've made a small wording tweak to make it plainer English - lmk what you think. 

2 further questions too:
 
1. Should we be having a similar line under buildingName and buildingNumber properties for clarity? 
2. If buildingName is left empty, should we saying there's no reason for a value expected in "subBuildingName"? Just to make it clear to the user about what they could/should be inputting? 

Happy to chat about this if needed or carry on the conversation here.

**Comment by PippaClarkGDS** [comment]
Sounds good - I'll put some time in our cals and will invite Elena (a new tech writer) along too so she can see a typical workflow

**Review by cmcnallygds — APPROVED** [review]
Looks good to me

**Comment by NathanD-GDS** [comment]
Looks great! Happy for it to be published.

**Review by sabrinaharris — APPROVED** [review]

**Pull request merged**
