### PR TITLE
creates details for the ui locales parameter for the user to select E…

### PR DESCRIPTION
**Pull request by PippaClarkGDS**
…nglish or Welsh

## Why

Queuing up the PR for when the Welsh content is live. Will mark as draft until the feature is ready to launch. 

## What

Includes details on the ui_locales parameter when making an auth request. 

## Technical writer support

Pippa is looped in. 

## How to review

Check the detail is accurate from a technical POV.

### CODE REVIEW

**Comment by dbes-gds** [comment]
Looks good to me 👍

**Comment by PippaClarkGDS** [comment]
cheers @dbes-gds - I'll get it to tech writer review now

**Review by NathanD-GDS — APPROVED** [review]
Looks good to me!

**Review by cmcnallygds — APPROVED** [review]

**Comment by PippaClarkGDS** [comment]
hi @dbes-gds - this PR is still in draft (but good to go otherwise). Do you know when we should push this live?

**Review by sabrinaharris — APPROVED** [review]

**Pull request merged**
